### ISSUE TITLE
Error report when using calibrate with query input

### ISSUE THREAD

**Issue by hezhao2024** [gaia-dpci/GaiaXPy#89]
I got an error report when following the tutorial of using 'calibrate' module to get XP spectra.
Tutorial reference: https://gaia-dpci.github.io/GaiaXPy-website/tutorials/Calibrator%20tutorial.html

My code following the tutorial:

```
query_input = "select TOP 2 source_id from gaiadr3.gaia_source where has_xp_continuous = 'True'"
calibrated_spectra, sampling = calibrate(query_input)
calibrated_spectra
```

Screenshots of the error report:

<img width="1232" alt="截屏2024-04-14 11 50 33" src="https://github.com/gaia-dpci/GaiaXPy/assets/160010812/610e8e99-5f39-4507-afae-72302f1d480b">
<img width="1210" alt="截屏2024-04-14 11 50 44" src="https://github.com/gaia-dpci/GaiaXPy/assets/160010812/10963b2c-d49b-42da-ac6e-45975b948ccd">

System:
Mac OS Monterey 12.4
JupyterLab
Python version: 3.9.7
gaiaxpy version: 2.1.0

**Comment by druzm** [comment]
Hello @hezhao2024

Thank you for the report. Did you install the package via pip? I've just pushed a fix for this issue to the dev branch of GaiaXPy. If you install the dev branch of the package [from source](https://gaiaxpy.readthedocs.io/en/latest/installation.html#from-source) instead, the problem should be gone.

The issue was caused by a difference in the table returned from the Archive. The program should be now more resilient to those changes.

**Comment by hezhao2024** [comment]
Hi Daniela, 

I cannot install GaiaXPy via the source because of an error report " No module named 'extension_helpers' ". 
I tried re-install with pip, the bug still exists. 

Best regards, 
He

**Comment by druzm** [comment]
Hi @hezhao2024 ,

Did you specifically clone the `dev` branch? If that's the case, with the virtual environment activated (as mentioned in the installation instructions), could you provide the output of the command `pip freeze`? It sounds like the problem is the version of one of the package dependencies.

Installing from PyPI won't fix the issue until a new release of the package is created.
